DROP TABLE IF EXISTS film_likes CASCADE;
DROP TABLE IF EXISTS status_code CASCADE;
DROP TABLE IF EXISTS mpa_rating CASCADE;
DROP TABLE IF EXISTS genres CASCADE;
DROP TABLE IF EXISTS friends CASCADE;
DROP TABLE IF EXISTS films CASCADE;
DROP TABLE IF EXISTS  users CASCADE;